### ISSUE TITLE
503 on user.messages.getMessages()

### ISSUE THREAD

**Issue by micahlt** [Zxnii/scratch-site-api#3]
I love what you're doing with this library!  However, on using the `user.messages.getMessages()` function, even when succesfully logged in, you recieve: 
```javascript
{
  body: '\n' +
    '<?xml version="1.0" encoding="utf-8"?>\n' +
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"\n' +
    ' "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n' +
    '<html>\n' +
    '  <head>\n' +
    '    <title>503 Service Unavailable</title>\n' +
    '  </head>\n' +
    '  <body>\n' +
    '    <h1>Error 503 Service Unavailable</h1>\n' +
    '    <p>Service Unavailable</p>\n' +
    '    <h3>Guru Mediation:</h3>\n' +
    '    <p>Details: cache-pwk4970-PWK 1611083193 449858740</p>\n' +
    '    <hr>\n' +
    '    <p>Varnish cache server</p>\n' +
    '  </body>\n' +
    '</html>\n',
  status: 503,
  json: {}
}
```
Visiting https://scratch.mit.edu/messages, however, works perfectly fine.

**Comment by xoogal** [comment]
Thanks for letting me know, I'll figure out what's going on and publish the fix. :)

Also sorry for the late reply, I've been very busy lately. The issue seems to be the same as what's causing comments on projects to not work so it shouldn't take too long to fix.

**Comment by xoogal** [comment]
it should work fine, are you making sure to pass offset and limit?
